name: Backend CI/CD

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Deploy backend
        run: |
          sudo mkdir -p /var/www/express-app/backend

          sudo rsync -av --delete \
            --exclude ".env" \
            --exclude "node_modules" \
            ./backend/ /var/www/express-app/backend/

          sudo chown -R ubuntu:ubuntu /var/www/express-app/backend

      - name: Create production environment file
        working-directory: /var/www/express-app/backend
        run: |
          echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Install production dependencies
        working-directory: /var/www/express-app/backend
        run: npm ci --omit=dev

      - name: Restart backend
        working-directory: /var/www/express-app/backend
        run: |
          pm2 restart BackendAPI || pm2 start server.js --name BackendAPI
          pm2 save
